### ISSUE TITLE
Improve the layout of the visual month view

### ISSUE THREAD

**Issue by Ordisoftware** [Ordisoftware/Hebrew-Calendar#1229]
**Part 1**
- [x] #1222
- [x] Refactoring and code review
- [x] Testing changes
- [x] Global testing and fixes
- [x] Packaging and validation
- [x] Deployment

**Part 2**
- [x] #1234
- [x] Refactoring and code review
- [x] Testing changes
- [x] Global testing and fixes
- [x] Packaging and validation
- [x] Deployment
