### ISSUE TITLE
Prepare the repository

### ISSUE THREAD

**Issue by Ordisoftware** [Ordisoftware/Hebrew-Calendar#4]
Create the software project on GitHub:
- [x] Prepare the repository #1 
- [x] Setup the repository #2 
- [x] Specify the license #3
